There was added one field into the users table and created authorisat…
Maksimilliano/MixApi pull request #2
Opened 2023-02-17 15:37 UTC by Maksimilliano

…ion methods and also added some routes.

2023-02-20 12:54 UTC, winter666 requested changes

2023-02-20 12:54 UTC, taleastromex commented on app/Http/Controllers/UserController.php
>  }
Предлагаю устроить рефакторинг)
Исходя из логики выполнения этот контроллер не просто создает что-то и тд но еще и авторизует, поэтому давай переименуем его в AuthController а методы create и store переименуем в registerView и register

2023-02-20 12:54 UTC, taleastromex commented on app/Http/Controllers/UserController.php
>          return redirect('/home');
В такие методы как store (позже переименуем в registration), login и logout буду приходить AJAX запросы, поэтому  возвращаемые типы данных для них немного не валидные, тут лучше использовать response()->json($response, $status); где в/вместо $response будет [ 'data' => 'value' ] (то есть данные возвращаемые в удачном или не удачном случае), и в/вместо $status будет код ответа (т.е. 200/400/401/500 итд)

2023-02-20 12:54 UTC, taleastromex commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->tinyInteger('is_admin')->default(0);
Необязательно это исправлять, но просто, на всякий случай у Blueprint есть метод boolean, что по сути является аналогом tinyInteger, так что можно использовать как $table->boolean('is_admin'), так и $table->tinyInteger('is_admin')

2023-02-20 13:27 UTC, Maksimilliano commented on app/Http/Controllers/UserController.php
>  }
Сделал, готово

2023-02-20 15:37 UTC, Maksimilliano commented on app/Http/Controllers/UserController.php
>          return redirect('/home');
Сделал, готово

2023-02-20 15:38 UTC, Maksimilliano commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->tinyInteger('is_admin')->default(0);
Пока решил так оставить, но суть понял)

2023-02-21 11:15 UTC, winter666 approved these changes

2023-02-21 19:39 UTC, merged